/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TimelineYearWeekRouteImport } from './routes/timeline/$year/$week'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineYearWeekRoute = TimelineYearWeekRouteImport.update({
  id: '/$year/$week',
  path: '/$year/$week',
  getParentRoute: () => TimelineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/quick': typeof QuickRoute
  '/reflect': typeof ReflectRoute
  '/timeline': typeof TimelineRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/timeline/$year/$week': typeof TimelineYearWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/quick': typeof QuickRoute
  '/reflect': typeof ReflectRoute
  '/timeline': typeof TimelineRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/timeline/$year/$week': typeof TimelineYearWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/quick': typeof QuickRoute
  '/reflect': typeof ReflectRoute
  '/timeline': typeof TimelineRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/timeline/$year/$week': typeof TimelineYearWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/quick'
    | '/reflect'
    | '/timeline'
    | '/api/chat'
    | '/timeline/$year/$week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/quick'
    | '/reflect'
    | '/timeline'
    | '/api/chat'
    | '/timeline/$year/$week'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/quick'
    | '/reflect'
    | '/timeline'
    | '/api/chat'
    | '/timeline/$year/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  QuickRoute: typeof QuickRoute
  ReflectRoute: typeof ReflectRoute
  TimelineRoute: typeof TimelineRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$year/$week': {
      id: '/timeline/$year/$week'
      path: '/$year/$week'
      fullPath: '/timeline/$year/$week'
      preLoaderRoute: typeof TimelineYearWeekRouteImport
      parentRoute: typeof TimelineRoute
    }
  }
}

interface TimelineRouteChildren {
  TimelineYearWeekRoute: typeof TimelineYearWeekRoute
}

const TimelineRouteChildren: TimelineRouteChildren = {
  TimelineYearWeekRoute: TimelineYearWeekRoute,
}

const TimelineRouteWithChildren = TimelineRoute._addFileChildren(
  TimelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  QuickRoute: QuickRoute,
  ReflectRoute: ReflectRoute,
  TimelineRoute: TimelineRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
