/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthedTimelineRouteImport } from './routes/_authed/timeline'
import { Route as AuthedReflectRouteImport } from './routes/_authed/reflect'
import { Route as AuthedQuickRouteImport } from './routes/_authed/quick'
import { Route as AuthedInsightsRouteImport } from './routes/_authed/insights'
import { Route as AuthedAboutMeRouteImport } from './routes/_authed/about-me'
import { Route as AuthedTimelineYearWeekRouteImport } from './routes/_authed/timeline/$year/$week'
import { Route as AuthedMonthsYearMonthRouteImport } from './routes/_authed/months/$year/$month'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTimelineRoute = AuthedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReflectRoute = AuthedReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQuickRoute = AuthedQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInsightsRoute = AuthedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAboutMeRoute = AuthedAboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimelineYearWeekRoute = AuthedTimelineYearWeekRouteImport.update({
  id: '/$year/$week',
  path: '/$year/$week',
  getParentRoute: () => AuthedTimelineRoute,
} as any)
const AuthedMonthsYearMonthRoute = AuthedMonthsYearMonthRouteImport.update({
  id: '/months/$year/$month',
  path: '/months/$year/$month',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/about-me': typeof AuthedAboutMeRoute
  '/insights': typeof AuthedInsightsRoute
  '/quick': typeof AuthedQuickRoute
  '/reflect': typeof AuthedReflectRoute
  '/timeline': typeof AuthedTimelineRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/months/$year/$month': typeof AuthedMonthsYearMonthRoute
  '/timeline/$year/$week': typeof AuthedTimelineYearWeekRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about-me': typeof AuthedAboutMeRoute
  '/insights': typeof AuthedInsightsRoute
  '/quick': typeof AuthedQuickRoute
  '/reflect': typeof AuthedReflectRoute
  '/timeline': typeof AuthedTimelineRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthedIndexRoute
  '/months/$year/$month': typeof AuthedMonthsYearMonthRoute
  '/timeline/$year/$week': typeof AuthedTimelineYearWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/about-me': typeof AuthedAboutMeRoute
  '/_authed/insights': typeof AuthedInsightsRoute
  '/_authed/quick': typeof AuthedQuickRoute
  '/_authed/reflect': typeof AuthedReflectRoute
  '/_authed/timeline': typeof AuthedTimelineRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/months/$year/$month': typeof AuthedMonthsYearMonthRoute
  '/_authed/timeline/$year/$week': typeof AuthedTimelineYearWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about-me'
    | '/insights'
    | '/quick'
    | '/reflect'
    | '/timeline'
    | '/api/chat'
    | '/months/$year/$month'
    | '/timeline/$year/$week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about-me'
    | '/insights'
    | '/quick'
    | '/reflect'
    | '/timeline'
    | '/api/chat'
    | '/'
    | '/months/$year/$month'
    | '/timeline/$year/$week'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/about-me'
    | '/_authed/insights'
    | '/_authed/quick'
    | '/_authed/reflect'
    | '/_authed/timeline'
    | '/api/chat'
    | '/_authed/'
    | '/_authed/months/$year/$month'
    | '/_authed/timeline/$year/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/timeline': {
      id: '/_authed/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthedTimelineRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reflect': {
      id: '/_authed/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AuthedReflectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/quick': {
      id: '/_authed/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof AuthedQuickRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/insights': {
      id: '/_authed/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthedInsightsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/about-me': {
      id: '/_authed/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AuthedAboutMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timeline/$year/$week': {
      id: '/_authed/timeline/$year/$week'
      path: '/$year/$week'
      fullPath: '/timeline/$year/$week'
      preLoaderRoute: typeof AuthedTimelineYearWeekRouteImport
      parentRoute: typeof AuthedTimelineRoute
    }
    '/_authed/months/$year/$month': {
      id: '/_authed/months/$year/$month'
      path: '/months/$year/$month'
      fullPath: '/months/$year/$month'
      preLoaderRoute: typeof AuthedMonthsYearMonthRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedTimelineRouteChildren {
  AuthedTimelineYearWeekRoute: typeof AuthedTimelineYearWeekRoute
}

const AuthedTimelineRouteChildren: AuthedTimelineRouteChildren = {
  AuthedTimelineYearWeekRoute: AuthedTimelineYearWeekRoute,
}

const AuthedTimelineRouteWithChildren = AuthedTimelineRoute._addFileChildren(
  AuthedTimelineRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAboutMeRoute: typeof AuthedAboutMeRoute
  AuthedInsightsRoute: typeof AuthedInsightsRoute
  AuthedQuickRoute: typeof AuthedQuickRoute
  AuthedReflectRoute: typeof AuthedReflectRoute
  AuthedTimelineRoute: typeof AuthedTimelineRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedMonthsYearMonthRoute: typeof AuthedMonthsYearMonthRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAboutMeRoute: AuthedAboutMeRoute,
  AuthedInsightsRoute: AuthedInsightsRoute,
  AuthedQuickRoute: AuthedQuickRoute,
  AuthedReflectRoute: AuthedReflectRoute,
  AuthedTimelineRoute: AuthedTimelineRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedMonthsYearMonthRoute: AuthedMonthsYearMonthRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
